window.FLASHCAR_UNITS = [
  {
    slug: "blumenau",
    nome: "Blumenau",
    uf: "SC",
    whatsapp: "554792210350",
    telefone: "(47) 92210-350",
    endereco: "R. Bahia, 2009 – Salto, Blumenau – SC, 89031-001",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/11/Blumenau.webp",
    sourceUrl: "https://flashcar.store/blumenau/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "jaragua-do-sul",
    nome: "Jaraguá do Sul",
    uf: "SC",
    whatsapp: "554792110144",
    telefone: "(47) 9211-0144",
    endereco: "Av. Pref. Waldemar Grubba, 2120 – Vila Lalau, Jaraguá do Sul – SC, 89256-501",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/11/Jaragua-do-Sul.webp",
    sourceUrl: "https://flashcar.store/jaragua-do-sul/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "tijucas",
    nome: "Tijucas",
    uf: "SC",
    whatsapp: "5547991154766",
    telefone: "(47) 99115-4766",
    endereco: "Av. Carlos Humberto Ternes, 304 – XV de Novembro, Tijucas – SC",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/11/Tijucas.webp",
    sourceUrl: "https://flashcar.store/tijucas/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "rio-do-sul",
    nome: "Rio do Sul",
    uf: "SC",
    whatsapp: "5547992473977",
    telefone: "(47) 99247-3977",
    endereco: "Estrada Blumenau, 460 – Bairro Santana, Rio do Sul – SC",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/11/Rio-do-Sul.webp",
    sourceUrl: "https://flashcar.store/rio-do-sul/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "concordia",
    nome: "Concórdia",
    uf: "SC",
    whatsapp: "5551996686612",
    telefone: "(51) 99668-6612",
    endereco: "R. Dona Francisca, 1120 – Saguaçu, Joinville – SC, 89221-006",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/11/Concordia.webp",
    sourceUrl: "https://flashcar.store/concordia/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "joinville",
    nome: "Joinville",
    uf: "SC",
    whatsapp: "5547992467298",
    telefone: "(47) 99246-7298",
    endereco: "R. Dona Francisca, 1120 – Saguaçu, Joinville – SC, 89221-006",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/12/Joinville-new.webp",
    sourceUrl: "https://flashcar.store/joinville/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "itajai",
    nome: "Itajaí",
    uf: "SC",
    whatsapp: "5547996795998",
    telefone: "(47) 99679-5998",
    endereco: "R. Stringari, 215 – São João, Itajaí – SC, 88305-110",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/12/Itajai-new.webp",
    sourceUrl: "https://flashcar.store/itajai/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "joacaba",
    nome: "Joaçaba",
    uf: "SC",
    whatsapp: "5549988581052",
    telefone: "(49) 98858-1052",
    endereco: "Av. Caetano Natal Branco, 307 – Centro, Joaçaba – SC",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/12/Joacaba-new.webp",
    sourceUrl: "https://flashcar.store/joacaba/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "chapeco",
    nome: "Chapecó",
    uf: "SC",
    whatsapp: "5549988703926",
    telefone: "(49) 98870-3926",
    endereco: "Rua Marechal Deodoro da Fonseca, 480 E – Chapecó – SC",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/12/Chapeco-new.webp",
    sourceUrl: "https://flashcar.store/chapeco/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "brusque",
    nome: "Brusque",
    uf: "SC",
    whatsapp: "5547920031499",
    telefone: "(47) 92003-1499",
    endereco: "Rua General Osório, 547 – Guarani, Brusque – SC",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2026/03/Brusque-new.webp",
    sourceUrl: "https://flashcar.store/brusque/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "ijui",
    nome: "Ijuí",
    uf: "RS",
    whatsapp: "5555997118788",
    telefone: "(55) 99963-9567",
    endereco: "Av. David José Martins, 461 – Sala B, Esquina Crisanto Leite – Ijuí – RS",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/12/Ijui-new.webp",
    sourceUrl: "https://flashcar.store/ijui/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "passo-fundo",
    nome: "Passo Fundo",
    uf: "RS",
    whatsapp: "5554996799737",
    telefone: "(54) 99679-9737",
    endereco: "Av. Brasil Oeste, 1921 – Bairro Boqueirão, Passo Fundo – RS",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/12/Passo-Fundo-new.webp",
    sourceUrl: "https://flashcar.store/passo-fundo/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "bauru",
    nome: "Bauru",
    uf: "SP",
    whatsapp: "5514981876400",
    telefone: "(14) 98187‑6400",
    endereco: "R. Pres. Kennedy, 9-47 - Vila Antarctica, Bauru - SP",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2026/06/Nova-unidade-reduzida.webp",
    sourceUrl: "https://flashcar.store/bauru/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?"
  },
  {
    slug: "campinas",
    nome: "Campinas",
    uf: "SP",
    whatsapp: "5519998608080",
    telefone: "(19) 99860-8080",
    endereco: "R. da Abolição, 2114 – Swift, Campinas – SP, 13041-445",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/12/Campinas-new.webp",
    sourceUrl: "https://flashcar.store/campinas/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?",
    flag: "Nova unidade"
  },
  {
    slug: "sao-jose-do-rio-preto",
    nome: "São José do Rio Preto",
    uf: "SP",
    whatsapp: "5517997056496",
    telefone: "(17) 99705-6496",
    endereco: "Rua Tiradentes, 3100 - Centro, São José do Rio Preto – SP",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2026/06/Nova-unidade-reduzida.webp",
    sourceUrl: "https://flashcar.store/sao-jose-do-rio-preto/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?",
    flag: "Nova unidade"
  },
  {
    slug: "goiania",
    nome: "Goiânia",
    uf: "GO",
    whatsapp: "554398126213",
    telefone: "(43) 98126-213",
    endereco: "Av. T8, 1072, QD. 60, LT. 5 – CEP 74210-040 – Setor Bueno, Goiânia – GO",
    horario: "Consulte atendimento da unidade pelo WhatsApp",
    foto: "https://flashcar.store/wp-content/uploads/2025/11/Goiania.webp",
    sourceUrl: "https://flashcar.store/goiania/",
    whatsappText: "Olá vi no site que vocês vendem meu veículo em até 60 minutos. Poderia me passar mais informações?",
    flag: "Nova unidade"
  }
];
